version: '3'
services:
  postgres:
    image: "postgres:13.4-alpine"
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: check_demo_development
    volumes:
      - ./data:/var/lib/postgresql/data
